-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_43_3_VITIS_LOOP_44_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_TVALID : IN STD_LOGIC;
    B_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_ce1 : OUT STD_LOGIC;
    B_we1 : OUT STD_LOGIC;
    B_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_1_ce1 : OUT STD_LOGIC;
    B_1_we1 : OUT STD_LOGIC;
    B_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_2_ce1 : OUT STD_LOGIC;
    B_2_we1 : OUT STD_LOGIC;
    B_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_3_ce1 : OUT STD_LOGIC;
    B_3_we1 : OUT STD_LOGIC;
    B_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_4_ce1 : OUT STD_LOGIC;
    B_4_we1 : OUT STD_LOGIC;
    B_4_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_5_ce1 : OUT STD_LOGIC;
    B_5_we1 : OUT STD_LOGIC;
    B_5_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_6_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_6_ce1 : OUT STD_LOGIC;
    B_6_we1 : OUT STD_LOGIC;
    B_6_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_7_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_7_ce1 : OUT STD_LOGIC;
    B_7_we1 : OUT STD_LOGIC;
    B_7_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_8_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_8_ce1 : OUT STD_LOGIC;
    B_8_we1 : OUT STD_LOGIC;
    B_8_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_9_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_9_ce1 : OUT STD_LOGIC;
    B_9_we1 : OUT STD_LOGIC;
    B_9_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_10_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_10_ce1 : OUT STD_LOGIC;
    B_10_we1 : OUT STD_LOGIC;
    B_10_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_11_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_11_ce1 : OUT STD_LOGIC;
    B_11_we1 : OUT STD_LOGIC;
    B_11_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_12_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_12_ce1 : OUT STD_LOGIC;
    B_12_we1 : OUT STD_LOGIC;
    B_12_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_13_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_13_ce1 : OUT STD_LOGIC;
    B_13_we1 : OUT STD_LOGIC;
    B_13_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_14_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_14_ce1 : OUT STD_LOGIC;
    B_14_we1 : OUT STD_LOGIC;
    B_14_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    B_15_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    B_15_ce1 : OUT STD_LOGIC;
    B_15_we1 : OUT STD_LOGIC;
    B_15_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_43_3_VITIS_LOOP_44_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln43_fu_448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_in_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_s_reg_595 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_s_reg_595_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln43_3_reg_615 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln46_fu_529_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln46_reg_619 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln46_1_fu_551_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_134 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln44_fu_535_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_138 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln43_1_fu_495_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten6_fu_142 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln43_1_fu_454_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (14 downto 0);
    signal B_14_we1_local : STD_LOGIC;
    signal B_14_ce1_local : STD_LOGIC;
    signal B_13_we1_local : STD_LOGIC;
    signal B_13_ce1_local : STD_LOGIC;
    signal B_12_we1_local : STD_LOGIC;
    signal B_12_ce1_local : STD_LOGIC;
    signal B_11_we1_local : STD_LOGIC;
    signal B_11_ce1_local : STD_LOGIC;
    signal B_10_we1_local : STD_LOGIC;
    signal B_10_ce1_local : STD_LOGIC;
    signal B_9_we1_local : STD_LOGIC;
    signal B_9_ce1_local : STD_LOGIC;
    signal B_8_we1_local : STD_LOGIC;
    signal B_8_ce1_local : STD_LOGIC;
    signal B_7_we1_local : STD_LOGIC;
    signal B_7_ce1_local : STD_LOGIC;
    signal B_6_we1_local : STD_LOGIC;
    signal B_6_ce1_local : STD_LOGIC;
    signal B_5_we1_local : STD_LOGIC;
    signal B_5_ce1_local : STD_LOGIC;
    signal B_4_we1_local : STD_LOGIC;
    signal B_4_ce1_local : STD_LOGIC;
    signal B_3_we1_local : STD_LOGIC;
    signal B_3_ce1_local : STD_LOGIC;
    signal B_2_we1_local : STD_LOGIC;
    signal B_2_ce1_local : STD_LOGIC;
    signal B_1_we1_local : STD_LOGIC;
    signal B_1_ce1_local : STD_LOGIC;
    signal B_we1_local : STD_LOGIC;
    signal B_ce1_local : STD_LOGIC;
    signal B_15_we1_local : STD_LOGIC;
    signal B_15_ce1_local : STD_LOGIC;
    signal icmp_ln44_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln43_fu_475_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln46_fu_503_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln43_fu_487_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_507_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln46_fu_525_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component matmul_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_138 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_138 <= select_ln43_1_fu_495_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln43_fu_448_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1))) then 
                    indvar_flatten6_fu_142 <= add_ln43_1_fu_454_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_142 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_134 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_134 <= add_ln44_fu_535_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln46_reg_619 <= add_ln46_fu_529_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                p_s_reg_595 <= stream_in_TDATA;
                p_s_reg_595_pp0_iter1_reg <= p_s_reg_595;
                trunc_ln43_3_reg_615 <= select_ln43_1_fu_495_p3(6 downto 3);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    B_10_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_10_ce1 <= B_10_ce1_local;

    B_10_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_10_ce1_local <= ap_const_logic_1;
        else 
            B_10_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_10_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_10_we1 <= B_10_we1_local;

    B_10_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_A))) then 
            B_10_we1_local <= ap_const_logic_1;
        else 
            B_10_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_11_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_11_ce1 <= B_11_ce1_local;

    B_11_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_11_ce1_local <= ap_const_logic_1;
        else 
            B_11_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_11_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_11_we1 <= B_11_we1_local;

    B_11_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_B))) then 
            B_11_we1_local <= ap_const_logic_1;
        else 
            B_11_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_12_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_12_ce1 <= B_12_ce1_local;

    B_12_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_12_ce1_local <= ap_const_logic_1;
        else 
            B_12_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_12_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_12_we1 <= B_12_we1_local;

    B_12_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_C))) then 
            B_12_we1_local <= ap_const_logic_1;
        else 
            B_12_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_13_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_13_ce1 <= B_13_ce1_local;

    B_13_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_13_ce1_local <= ap_const_logic_1;
        else 
            B_13_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_13_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_13_we1 <= B_13_we1_local;

    B_13_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_D))) then 
            B_13_we1_local <= ap_const_logic_1;
        else 
            B_13_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_14_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_14_ce1 <= B_14_ce1_local;

    B_14_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_14_ce1_local <= ap_const_logic_1;
        else 
            B_14_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_14_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_14_we1 <= B_14_we1_local;

    B_14_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_E))) then 
            B_14_we1_local <= ap_const_logic_1;
        else 
            B_14_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_15_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_15_ce1 <= B_15_ce1_local;

    B_15_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_15_ce1_local <= ap_const_logic_1;
        else 
            B_15_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_15_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_15_we1 <= B_15_we1_local;

    B_15_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_F))) then 
            B_15_we1_local <= ap_const_logic_1;
        else 
            B_15_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_1_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_1_ce1 <= B_1_ce1_local;

    B_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_1_ce1_local <= ap_const_logic_1;
        else 
            B_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_1_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_1_we1 <= B_1_we1_local;

    B_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_1))) then 
            B_1_we1_local <= ap_const_logic_1;
        else 
            B_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_2_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_2_ce1 <= B_2_ce1_local;

    B_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_2_ce1_local <= ap_const_logic_1;
        else 
            B_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_2_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_2_we1 <= B_2_we1_local;

    B_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_2))) then 
            B_2_we1_local <= ap_const_logic_1;
        else 
            B_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_3_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_3_ce1 <= B_3_ce1_local;

    B_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_3_ce1_local <= ap_const_logic_1;
        else 
            B_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_3_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_3_we1 <= B_3_we1_local;

    B_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_3))) then 
            B_3_we1_local <= ap_const_logic_1;
        else 
            B_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_4_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_4_ce1 <= B_4_ce1_local;

    B_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_4_ce1_local <= ap_const_logic_1;
        else 
            B_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_4_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_4_we1 <= B_4_we1_local;

    B_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_4))) then 
            B_4_we1_local <= ap_const_logic_1;
        else 
            B_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_5_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_5_ce1 <= B_5_ce1_local;

    B_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_5_ce1_local <= ap_const_logic_1;
        else 
            B_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_5_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_5_we1 <= B_5_we1_local;

    B_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_5))) then 
            B_5_we1_local <= ap_const_logic_1;
        else 
            B_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_6_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_6_ce1 <= B_6_ce1_local;

    B_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_6_ce1_local <= ap_const_logic_1;
        else 
            B_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_6_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_6_we1 <= B_6_we1_local;

    B_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_6))) then 
            B_6_we1_local <= ap_const_logic_1;
        else 
            B_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_7_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_7_ce1 <= B_7_ce1_local;

    B_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_7_ce1_local <= ap_const_logic_1;
        else 
            B_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_7_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_7_we1 <= B_7_we1_local;

    B_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_7))) then 
            B_7_we1_local <= ap_const_logic_1;
        else 
            B_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_8_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_8_ce1 <= B_8_ce1_local;

    B_8_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_8_ce1_local <= ap_const_logic_1;
        else 
            B_8_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_8_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_8_we1 <= B_8_we1_local;

    B_8_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_8))) then 
            B_8_we1_local <= ap_const_logic_1;
        else 
            B_8_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_9_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_9_ce1 <= B_9_ce1_local;

    B_9_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_9_ce1_local <= ap_const_logic_1;
        else 
            B_9_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_9_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_9_we1 <= B_9_we1_local;

    B_9_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_9))) then 
            B_9_we1_local <= ap_const_logic_1;
        else 
            B_9_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_address1 <= zext_ln46_1_fu_551_p1(10 - 1 downto 0);
    B_ce1 <= B_ce1_local;

    B_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            B_ce1_local <= ap_const_logic_1;
        else 
            B_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    B_d1 <= p_s_reg_595_pp0_iter1_reg;
    B_we1 <= B_we1_local;

    B_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln43_3_reg_615)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln43_3_reg_615 = ap_const_lv4_0))) then 
            B_we1_local <= ap_const_logic_1;
        else 
            B_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln43_1_fu_454_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv15_1));
    add_ln43_fu_475_p2 <= std_logic_vector(unsigned(i_fu_138) + unsigned(ap_const_lv8_1));
    add_ln44_fu_535_p2 <= std_logic_vector(unsigned(select_ln43_fu_487_p3) + unsigned(ap_const_lv8_1));
    add_ln46_fu_529_p2 <= std_logic_vector(unsigned(tmp_2_fu_507_p3) + unsigned(zext_ln46_fu_525_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(stream_in_TVALID, icmp_ln43_fu_448_p2)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((icmp_ln43_fu_448_p2 = ap_const_lv1_0) and (stream_in_TVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln43_fu_448_p2, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln43_fu_448_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_142)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_142;
        end if; 
    end process;

    icmp_ln43_fu_448_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv15_4000) else "0";
    icmp_ln44_fu_481_p2 <= "1" when (j_fu_134 = ap_const_lv8_80) else "0";
    select_ln43_1_fu_495_p3 <= 
        add_ln43_fu_475_p2 when (icmp_ln44_fu_481_p2(0) = '1') else 
        i_fu_138;
    select_ln43_fu_487_p3 <= 
        ap_const_lv8_0 when (icmp_ln44_fu_481_p2(0) = '1') else 
        j_fu_134;

    stream_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, stream_in_TVALID, icmp_ln43_fu_448_p2, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln43_fu_448_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TDATA_blk_n <= stream_in_TVALID;
        else 
            stream_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln43_fu_448_p2, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln43_fu_448_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_in_TREADY <= ap_const_logic_1;
        else 
            stream_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    tmp_2_fu_507_p3 <= (trunc_ln46_fu_503_p1 & ap_const_lv7_0);
    trunc_ln46_fu_503_p1 <= select_ln43_1_fu_495_p3(3 - 1 downto 0);
    zext_ln46_1_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln46_reg_619),64));
    zext_ln46_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln43_fu_487_p3),10));
end behav;
