// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_43_3_VITIS_LOOP_44_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_TVALID,
        B_address1,
        B_ce1,
        B_we1,
        B_d1,
        B_1_address1,
        B_1_ce1,
        B_1_we1,
        B_1_d1,
        B_2_address1,
        B_2_ce1,
        B_2_we1,
        B_2_d1,
        B_3_address1,
        B_3_ce1,
        B_3_we1,
        B_3_d1,
        B_4_address1,
        B_4_ce1,
        B_4_we1,
        B_4_d1,
        B_5_address1,
        B_5_ce1,
        B_5_we1,
        B_5_d1,
        B_6_address1,
        B_6_ce1,
        B_6_we1,
        B_6_d1,
        B_7_address1,
        B_7_ce1,
        B_7_we1,
        B_7_d1,
        B_8_address1,
        B_8_ce1,
        B_8_we1,
        B_8_d1,
        B_9_address1,
        B_9_ce1,
        B_9_we1,
        B_9_d1,
        B_10_address1,
        B_10_ce1,
        B_10_we1,
        B_10_d1,
        B_11_address1,
        B_11_ce1,
        B_11_we1,
        B_11_d1,
        B_12_address1,
        B_12_ce1,
        B_12_we1,
        B_12_d1,
        B_13_address1,
        B_13_ce1,
        B_13_we1,
        B_13_d1,
        B_14_address1,
        B_14_ce1,
        B_14_we1,
        B_14_d1,
        B_15_address1,
        B_15_ce1,
        B_15_we1,
        B_15_d1,
        stream_in_TDATA,
        stream_in_TREADY,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_TVALID;
output  [9:0] B_address1;
output   B_ce1;
output   B_we1;
output  [31:0] B_d1;
output  [9:0] B_1_address1;
output   B_1_ce1;
output   B_1_we1;
output  [31:0] B_1_d1;
output  [9:0] B_2_address1;
output   B_2_ce1;
output   B_2_we1;
output  [31:0] B_2_d1;
output  [9:0] B_3_address1;
output   B_3_ce1;
output   B_3_we1;
output  [31:0] B_3_d1;
output  [9:0] B_4_address1;
output   B_4_ce1;
output   B_4_we1;
output  [31:0] B_4_d1;
output  [9:0] B_5_address1;
output   B_5_ce1;
output   B_5_we1;
output  [31:0] B_5_d1;
output  [9:0] B_6_address1;
output   B_6_ce1;
output   B_6_we1;
output  [31:0] B_6_d1;
output  [9:0] B_7_address1;
output   B_7_ce1;
output   B_7_we1;
output  [31:0] B_7_d1;
output  [9:0] B_8_address1;
output   B_8_ce1;
output   B_8_we1;
output  [31:0] B_8_d1;
output  [9:0] B_9_address1;
output   B_9_ce1;
output   B_9_we1;
output  [31:0] B_9_d1;
output  [9:0] B_10_address1;
output   B_10_ce1;
output   B_10_we1;
output  [31:0] B_10_d1;
output  [9:0] B_11_address1;
output   B_11_ce1;
output   B_11_we1;
output  [31:0] B_11_d1;
output  [9:0] B_12_address1;
output   B_12_ce1;
output   B_12_we1;
output  [31:0] B_12_d1;
output  [9:0] B_13_address1;
output   B_13_ce1;
output   B_13_we1;
output  [31:0] B_13_d1;
output  [9:0] B_14_address1;
output   B_14_ce1;
output   B_14_we1;
output  [31:0] B_14_d1;
output  [9:0] B_15_address1;
output   B_15_ce1;
output   B_15_we1;
output  [31:0] B_15_d1;
input  [31:0] stream_in_TDATA;
output   stream_in_TREADY;
input  [3:0] stream_in_TKEEP;
input  [3:0] stream_in_TSTRB;
input  [0:0] stream_in_TLAST;

reg ap_idle;
reg stream_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln43_fu_448_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_s_reg_595;
reg   [31:0] p_s_reg_595_pp0_iter1_reg;
reg   [3:0] trunc_ln43_3_reg_615;
wire   [9:0] add_ln46_fu_529_p2;
reg   [9:0] add_ln46_reg_619;
wire   [63:0] zext_ln46_1_fu_551_p1;
reg   [7:0] j_fu_134;
wire   [7:0] add_ln44_fu_535_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_138;
wire   [7:0] select_ln43_1_fu_495_p3;
reg   [14:0] indvar_flatten6_fu_142;
wire   [14:0] add_ln43_1_fu_454_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    B_14_we1_local;
reg    B_14_ce1_local;
reg    B_13_we1_local;
reg    B_13_ce1_local;
reg    B_12_we1_local;
reg    B_12_ce1_local;
reg    B_11_we1_local;
reg    B_11_ce1_local;
reg    B_10_we1_local;
reg    B_10_ce1_local;
reg    B_9_we1_local;
reg    B_9_ce1_local;
reg    B_8_we1_local;
reg    B_8_ce1_local;
reg    B_7_we1_local;
reg    B_7_ce1_local;
reg    B_6_we1_local;
reg    B_6_ce1_local;
reg    B_5_we1_local;
reg    B_5_ce1_local;
reg    B_4_we1_local;
reg    B_4_ce1_local;
reg    B_3_we1_local;
reg    B_3_ce1_local;
reg    B_2_we1_local;
reg    B_2_ce1_local;
reg    B_1_we1_local;
reg    B_1_ce1_local;
reg    B_we1_local;
reg    B_ce1_local;
reg    B_15_we1_local;
reg    B_15_ce1_local;
wire   [0:0] icmp_ln44_fu_481_p2;
wire   [7:0] add_ln43_fu_475_p2;
wire   [2:0] trunc_ln46_fu_503_p1;
wire   [7:0] select_ln43_fu_487_p3;
wire   [9:0] tmp_2_fu_507_p3;
wire   [9:0] zext_ln46_fu_525_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_134 = 8'd0;
#0 i_fu_138 = 8'd0;
#0 indvar_flatten6_fu_142 = 15'd0;
#0 ap_done_reg = 1'b0;
end

matmul_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_138 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_138 <= select_ln43_1_fu_495_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln43_fu_448_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            indvar_flatten6_fu_142 <= add_ln43_1_fu_454_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_142 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_134 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_134 <= add_ln44_fu_535_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_reg_619 <= add_ln46_fu_529_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        p_s_reg_595 <= stream_in_TDATA;
        p_s_reg_595_pp0_iter1_reg <= p_s_reg_595;
        trunc_ln43_3_reg_615 <= {{select_ln43_1_fu_495_p3[6:3]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_10_ce1_local = 1'b1;
    end else begin
        B_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd10))) begin
        B_10_we1_local = 1'b1;
    end else begin
        B_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_11_ce1_local = 1'b1;
    end else begin
        B_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd11))) begin
        B_11_we1_local = 1'b1;
    end else begin
        B_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_12_ce1_local = 1'b1;
    end else begin
        B_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd12))) begin
        B_12_we1_local = 1'b1;
    end else begin
        B_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_13_ce1_local = 1'b1;
    end else begin
        B_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd13))) begin
        B_13_we1_local = 1'b1;
    end else begin
        B_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_14_ce1_local = 1'b1;
    end else begin
        B_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd14))) begin
        B_14_we1_local = 1'b1;
    end else begin
        B_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_15_ce1_local = 1'b1;
    end else begin
        B_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd15))) begin
        B_15_we1_local = 1'b1;
    end else begin
        B_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_1_ce1_local = 1'b1;
    end else begin
        B_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd1))) begin
        B_1_we1_local = 1'b1;
    end else begin
        B_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_2_ce1_local = 1'b1;
    end else begin
        B_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd2))) begin
        B_2_we1_local = 1'b1;
    end else begin
        B_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_3_ce1_local = 1'b1;
    end else begin
        B_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd3))) begin
        B_3_we1_local = 1'b1;
    end else begin
        B_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_4_ce1_local = 1'b1;
    end else begin
        B_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd4))) begin
        B_4_we1_local = 1'b1;
    end else begin
        B_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_5_ce1_local = 1'b1;
    end else begin
        B_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd5))) begin
        B_5_we1_local = 1'b1;
    end else begin
        B_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_6_ce1_local = 1'b1;
    end else begin
        B_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd6))) begin
        B_6_we1_local = 1'b1;
    end else begin
        B_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_7_ce1_local = 1'b1;
    end else begin
        B_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd7))) begin
        B_7_we1_local = 1'b1;
    end else begin
        B_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_8_ce1_local = 1'b1;
    end else begin
        B_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd8))) begin
        B_8_we1_local = 1'b1;
    end else begin
        B_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_9_ce1_local = 1'b1;
    end else begin
        B_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd9))) begin
        B_9_we1_local = 1'b1;
    end else begin
        B_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        B_ce1_local = 1'b1;
    end else begin
        B_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln43_3_reg_615 == 4'd0))) begin
        B_we1_local = 1'b1;
    end else begin
        B_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln43_fu_448_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_142;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln43_fu_448_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TDATA_blk_n = stream_in_TVALID;
    end else begin
        stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln43_fu_448_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TREADY = 1'b1;
    end else begin
        stream_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_10_address1 = zext_ln46_1_fu_551_p1;

assign B_10_ce1 = B_10_ce1_local;

assign B_10_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_10_we1 = B_10_we1_local;

assign B_11_address1 = zext_ln46_1_fu_551_p1;

assign B_11_ce1 = B_11_ce1_local;

assign B_11_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_11_we1 = B_11_we1_local;

assign B_12_address1 = zext_ln46_1_fu_551_p1;

assign B_12_ce1 = B_12_ce1_local;

assign B_12_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_12_we1 = B_12_we1_local;

assign B_13_address1 = zext_ln46_1_fu_551_p1;

assign B_13_ce1 = B_13_ce1_local;

assign B_13_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_13_we1 = B_13_we1_local;

assign B_14_address1 = zext_ln46_1_fu_551_p1;

assign B_14_ce1 = B_14_ce1_local;

assign B_14_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_14_we1 = B_14_we1_local;

assign B_15_address1 = zext_ln46_1_fu_551_p1;

assign B_15_ce1 = B_15_ce1_local;

assign B_15_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_15_we1 = B_15_we1_local;

assign B_1_address1 = zext_ln46_1_fu_551_p1;

assign B_1_ce1 = B_1_ce1_local;

assign B_1_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_1_we1 = B_1_we1_local;

assign B_2_address1 = zext_ln46_1_fu_551_p1;

assign B_2_ce1 = B_2_ce1_local;

assign B_2_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_2_we1 = B_2_we1_local;

assign B_3_address1 = zext_ln46_1_fu_551_p1;

assign B_3_ce1 = B_3_ce1_local;

assign B_3_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_3_we1 = B_3_we1_local;

assign B_4_address1 = zext_ln46_1_fu_551_p1;

assign B_4_ce1 = B_4_ce1_local;

assign B_4_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_4_we1 = B_4_we1_local;

assign B_5_address1 = zext_ln46_1_fu_551_p1;

assign B_5_ce1 = B_5_ce1_local;

assign B_5_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_5_we1 = B_5_we1_local;

assign B_6_address1 = zext_ln46_1_fu_551_p1;

assign B_6_ce1 = B_6_ce1_local;

assign B_6_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_6_we1 = B_6_we1_local;

assign B_7_address1 = zext_ln46_1_fu_551_p1;

assign B_7_ce1 = B_7_ce1_local;

assign B_7_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_7_we1 = B_7_we1_local;

assign B_8_address1 = zext_ln46_1_fu_551_p1;

assign B_8_ce1 = B_8_ce1_local;

assign B_8_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_8_we1 = B_8_we1_local;

assign B_9_address1 = zext_ln46_1_fu_551_p1;

assign B_9_ce1 = B_9_ce1_local;

assign B_9_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_9_we1 = B_9_we1_local;

assign B_address1 = zext_ln46_1_fu_551_p1;

assign B_ce1 = B_ce1_local;

assign B_d1 = p_s_reg_595_pp0_iter1_reg;

assign B_we1 = B_we1_local;

assign add_ln43_1_fu_454_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 15'd1);

assign add_ln43_fu_475_p2 = (i_fu_138 + 8'd1);

assign add_ln44_fu_535_p2 = (select_ln43_fu_487_p3 + 8'd1);

assign add_ln46_fu_529_p2 = (tmp_2_fu_507_p3 + zext_ln46_fu_525_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln43_fu_448_p2 == 1'd0) & (stream_in_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln43_fu_448_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_481_p2 = ((j_fu_134 == 8'd128) ? 1'b1 : 1'b0);

assign select_ln43_1_fu_495_p3 = ((icmp_ln44_fu_481_p2[0:0] == 1'b1) ? add_ln43_fu_475_p2 : i_fu_138);

assign select_ln43_fu_487_p3 = ((icmp_ln44_fu_481_p2[0:0] == 1'b1) ? 8'd0 : j_fu_134);

assign tmp_2_fu_507_p3 = {{trunc_ln46_fu_503_p1}, {7'd0}};

assign trunc_ln46_fu_503_p1 = select_ln43_1_fu_495_p3[2:0];

assign zext_ln46_1_fu_551_p1 = add_ln46_reg_619;

assign zext_ln46_fu_525_p1 = select_ln43_fu_487_p3;

endmodule //matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_43_3_VITIS_LOOP_44_4
