// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_35_1_VITIS_LOOP_36_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_TVALID,
        A_address1,
        A_ce1,
        A_we1,
        A_d1,
        A_1_address1,
        A_1_ce1,
        A_1_we1,
        A_1_d1,
        A_2_address1,
        A_2_ce1,
        A_2_we1,
        A_2_d1,
        A_3_address1,
        A_3_ce1,
        A_3_we1,
        A_3_d1,
        A_4_address1,
        A_4_ce1,
        A_4_we1,
        A_4_d1,
        A_5_address1,
        A_5_ce1,
        A_5_we1,
        A_5_d1,
        A_6_address1,
        A_6_ce1,
        A_6_we1,
        A_6_d1,
        A_7_address1,
        A_7_ce1,
        A_7_we1,
        A_7_d1,
        A_8_address1,
        A_8_ce1,
        A_8_we1,
        A_8_d1,
        A_9_address1,
        A_9_ce1,
        A_9_we1,
        A_9_d1,
        A_10_address1,
        A_10_ce1,
        A_10_we1,
        A_10_d1,
        A_11_address1,
        A_11_ce1,
        A_11_we1,
        A_11_d1,
        A_12_address1,
        A_12_ce1,
        A_12_we1,
        A_12_d1,
        A_13_address1,
        A_13_ce1,
        A_13_we1,
        A_13_d1,
        A_14_address1,
        A_14_ce1,
        A_14_we1,
        A_14_d1,
        A_15_address1,
        A_15_ce1,
        A_15_we1,
        A_15_d1,
        stream_in_TDATA,
        stream_in_TREADY,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_in_TVALID;
output  [9:0] A_address1;
output   A_ce1;
output   A_we1;
output  [31:0] A_d1;
output  [9:0] A_1_address1;
output   A_1_ce1;
output   A_1_we1;
output  [31:0] A_1_d1;
output  [9:0] A_2_address1;
output   A_2_ce1;
output   A_2_we1;
output  [31:0] A_2_d1;
output  [9:0] A_3_address1;
output   A_3_ce1;
output   A_3_we1;
output  [31:0] A_3_d1;
output  [9:0] A_4_address1;
output   A_4_ce1;
output   A_4_we1;
output  [31:0] A_4_d1;
output  [9:0] A_5_address1;
output   A_5_ce1;
output   A_5_we1;
output  [31:0] A_5_d1;
output  [9:0] A_6_address1;
output   A_6_ce1;
output   A_6_we1;
output  [31:0] A_6_d1;
output  [9:0] A_7_address1;
output   A_7_ce1;
output   A_7_we1;
output  [31:0] A_7_d1;
output  [9:0] A_8_address1;
output   A_8_ce1;
output   A_8_we1;
output  [31:0] A_8_d1;
output  [9:0] A_9_address1;
output   A_9_ce1;
output   A_9_we1;
output  [31:0] A_9_d1;
output  [9:0] A_10_address1;
output   A_10_ce1;
output   A_10_we1;
output  [31:0] A_10_d1;
output  [9:0] A_11_address1;
output   A_11_ce1;
output   A_11_we1;
output  [31:0] A_11_d1;
output  [9:0] A_12_address1;
output   A_12_ce1;
output   A_12_we1;
output  [31:0] A_12_d1;
output  [9:0] A_13_address1;
output   A_13_ce1;
output   A_13_we1;
output  [31:0] A_13_d1;
output  [9:0] A_14_address1;
output   A_14_ce1;
output   A_14_we1;
output  [31:0] A_14_d1;
output  [9:0] A_15_address1;
output   A_15_ce1;
output   A_15_we1;
output  [31:0] A_15_d1;
input  [31:0] stream_in_TDATA;
output   stream_in_TREADY;
input  [3:0] stream_in_TKEEP;
input  [3:0] stream_in_TSTRB;
input  [0:0] stream_in_TLAST;

reg ap_idle;
reg stream_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln35_fu_446_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_s_reg_586;
reg   [31:0] p_s_reg_586_pp0_iter1_reg;
wire   [0:0] icmp_ln36_fu_470_p2;
reg   [0:0] icmp_ln36_reg_606;
wire   [2:0] trunc_ln36_1_fu_484_p1;
reg   [2:0] trunc_ln36_1_reg_611;
reg   [3:0] trunc_ln_reg_616;
wire   [63:0] zext_ln38_fu_536_p1;
reg   [7:0] j_fu_132;
wire   [7:0] add_ln36_fu_498_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_136;
wire   [7:0] select_ln35_1_fu_518_p3;
reg   [14:0] indvar_flatten_fu_140;
wire   [14:0] add_ln35_1_fu_452_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
reg    A_14_we1_local;
reg    A_14_ce1_local;
reg    A_13_we1_local;
reg    A_13_ce1_local;
reg    A_12_we1_local;
reg    A_12_ce1_local;
reg    A_11_we1_local;
reg    A_11_ce1_local;
reg    A_10_we1_local;
reg    A_10_ce1_local;
reg    A_9_we1_local;
reg    A_9_ce1_local;
reg    A_8_we1_local;
reg    A_8_ce1_local;
reg    A_7_we1_local;
reg    A_7_ce1_local;
reg    A_6_we1_local;
reg    A_6_ce1_local;
reg    A_5_we1_local;
reg    A_5_ce1_local;
reg    A_4_we1_local;
reg    A_4_ce1_local;
reg    A_3_we1_local;
reg    A_3_ce1_local;
reg    A_2_we1_local;
reg    A_2_ce1_local;
reg    A_1_we1_local;
reg    A_1_ce1_local;
reg    A_we1_local;
reg    A_ce1_local;
reg    A_15_we1_local;
reg    A_15_ce1_local;
wire   [7:0] select_ln35_fu_476_p3;
wire   [7:0] add_ln35_fu_512_p2;
wire   [6:0] trunc_ln36_fu_525_p1;
wire   [9:0] tmp_fu_529_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_132 = 8'd0;
#0 i_fu_136 = 8'd0;
#0 indvar_flatten_fu_140 = 15'd0;
#0 ap_done_reg = 1'b0;
end

matmul_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_fu_136 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_136 <= select_ln35_1_fu_518_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_446_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            indvar_flatten_fu_140 <= add_ln35_1_fu_452_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_140 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_132 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_132 <= add_ln36_fu_498_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln36_reg_606 <= icmp_ln36_fu_470_p2;
        p_s_reg_586 <= stream_in_TDATA;
        p_s_reg_586_pp0_iter1_reg <= p_s_reg_586;
        trunc_ln36_1_reg_611 <= trunc_ln36_1_fu_484_p1;
        trunc_ln_reg_616 <= {{select_ln35_fu_476_p3[6:3]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_10_ce1_local = 1'b1;
    end else begin
        A_10_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd10))) begin
        A_10_we1_local = 1'b1;
    end else begin
        A_10_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_11_ce1_local = 1'b1;
    end else begin
        A_11_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd11))) begin
        A_11_we1_local = 1'b1;
    end else begin
        A_11_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_12_ce1_local = 1'b1;
    end else begin
        A_12_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd12))) begin
        A_12_we1_local = 1'b1;
    end else begin
        A_12_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_13_ce1_local = 1'b1;
    end else begin
        A_13_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd13))) begin
        A_13_we1_local = 1'b1;
    end else begin
        A_13_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_14_ce1_local = 1'b1;
    end else begin
        A_14_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd14))) begin
        A_14_we1_local = 1'b1;
    end else begin
        A_14_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_15_ce1_local = 1'b1;
    end else begin
        A_15_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd15))) begin
        A_15_we1_local = 1'b1;
    end else begin
        A_15_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_1_ce1_local = 1'b1;
    end else begin
        A_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd1))) begin
        A_1_we1_local = 1'b1;
    end else begin
        A_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_2_ce1_local = 1'b1;
    end else begin
        A_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd2))) begin
        A_2_we1_local = 1'b1;
    end else begin
        A_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_3_ce1_local = 1'b1;
    end else begin
        A_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd3))) begin
        A_3_we1_local = 1'b1;
    end else begin
        A_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_4_ce1_local = 1'b1;
    end else begin
        A_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd4))) begin
        A_4_we1_local = 1'b1;
    end else begin
        A_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_5_ce1_local = 1'b1;
    end else begin
        A_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd5))) begin
        A_5_we1_local = 1'b1;
    end else begin
        A_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_6_ce1_local = 1'b1;
    end else begin
        A_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd6))) begin
        A_6_we1_local = 1'b1;
    end else begin
        A_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_7_ce1_local = 1'b1;
    end else begin
        A_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd7))) begin
        A_7_we1_local = 1'b1;
    end else begin
        A_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_8_ce1_local = 1'b1;
    end else begin
        A_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd8))) begin
        A_8_we1_local = 1'b1;
    end else begin
        A_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_9_ce1_local = 1'b1;
    end else begin
        A_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd9))) begin
        A_9_we1_local = 1'b1;
    end else begin
        A_9_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_ce1_local = 1'b1;
    end else begin
        A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (trunc_ln_reg_616 == 4'd0))) begin
        A_we1_local = 1'b1;
    end else begin
        A_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln35_fu_446_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln35_fu_446_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TDATA_blk_n = stream_in_TVALID;
    end else begin
        stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln35_fu_446_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_TREADY = 1'b1;
    end else begin
        stream_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_10_address1 = zext_ln38_fu_536_p1;

assign A_10_ce1 = A_10_ce1_local;

assign A_10_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_10_we1 = A_10_we1_local;

assign A_11_address1 = zext_ln38_fu_536_p1;

assign A_11_ce1 = A_11_ce1_local;

assign A_11_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_11_we1 = A_11_we1_local;

assign A_12_address1 = zext_ln38_fu_536_p1;

assign A_12_ce1 = A_12_ce1_local;

assign A_12_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_12_we1 = A_12_we1_local;

assign A_13_address1 = zext_ln38_fu_536_p1;

assign A_13_ce1 = A_13_ce1_local;

assign A_13_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_13_we1 = A_13_we1_local;

assign A_14_address1 = zext_ln38_fu_536_p1;

assign A_14_ce1 = A_14_ce1_local;

assign A_14_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_14_we1 = A_14_we1_local;

assign A_15_address1 = zext_ln38_fu_536_p1;

assign A_15_ce1 = A_15_ce1_local;

assign A_15_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_15_we1 = A_15_we1_local;

assign A_1_address1 = zext_ln38_fu_536_p1;

assign A_1_ce1 = A_1_ce1_local;

assign A_1_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_1_we1 = A_1_we1_local;

assign A_2_address1 = zext_ln38_fu_536_p1;

assign A_2_ce1 = A_2_ce1_local;

assign A_2_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_2_we1 = A_2_we1_local;

assign A_3_address1 = zext_ln38_fu_536_p1;

assign A_3_ce1 = A_3_ce1_local;

assign A_3_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_3_we1 = A_3_we1_local;

assign A_4_address1 = zext_ln38_fu_536_p1;

assign A_4_ce1 = A_4_ce1_local;

assign A_4_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_4_we1 = A_4_we1_local;

assign A_5_address1 = zext_ln38_fu_536_p1;

assign A_5_ce1 = A_5_ce1_local;

assign A_5_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_5_we1 = A_5_we1_local;

assign A_6_address1 = zext_ln38_fu_536_p1;

assign A_6_ce1 = A_6_ce1_local;

assign A_6_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_6_we1 = A_6_we1_local;

assign A_7_address1 = zext_ln38_fu_536_p1;

assign A_7_ce1 = A_7_ce1_local;

assign A_7_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_7_we1 = A_7_we1_local;

assign A_8_address1 = zext_ln38_fu_536_p1;

assign A_8_ce1 = A_8_ce1_local;

assign A_8_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_8_we1 = A_8_we1_local;

assign A_9_address1 = zext_ln38_fu_536_p1;

assign A_9_ce1 = A_9_ce1_local;

assign A_9_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_9_we1 = A_9_we1_local;

assign A_address1 = zext_ln38_fu_536_p1;

assign A_ce1 = A_ce1_local;

assign A_d1 = p_s_reg_586_pp0_iter1_reg;

assign A_we1 = A_we1_local;

assign add_ln35_1_fu_452_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln35_fu_512_p2 = (i_fu_136 + 8'd1);

assign add_ln36_fu_498_p2 = (select_ln35_fu_476_p3 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln35_fu_446_p2 == 1'd0) & (stream_in_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln35_fu_446_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_470_p2 = ((j_fu_132 == 8'd128) ? 1'b1 : 1'b0);

assign select_ln35_1_fu_518_p3 = ((icmp_ln36_reg_606[0:0] == 1'b1) ? add_ln35_fu_512_p2 : i_fu_136);

assign select_ln35_fu_476_p3 = ((icmp_ln36_fu_470_p2[0:0] == 1'b1) ? 8'd0 : j_fu_132);

assign tmp_fu_529_p3 = {{trunc_ln36_fu_525_p1}, {trunc_ln36_1_reg_611}};

assign trunc_ln36_1_fu_484_p1 = select_ln35_fu_476_p3[2:0];

assign trunc_ln36_fu_525_p1 = select_ln35_1_fu_518_p3[6:0];

assign zext_ln38_fu_536_p1 = tmp_fu_529_p3;

endmodule //matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_35_1_VITIS_LOOP_36_2
