// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_64_8_VITIS_LOOP_65_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_out_TREADY,
        C_address0,
        C_ce0,
        C_q0,
        C_1_address0,
        C_1_ce0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_q0,
        C_4_address0,
        C_4_ce0,
        C_4_q0,
        C_5_address0,
        C_5_ce0,
        C_5_q0,
        C_6_address0,
        C_6_ce0,
        C_6_q0,
        C_7_address0,
        C_7_ce0,
        C_7_q0,
        C_8_address0,
        C_8_ce0,
        C_8_q0,
        C_9_address0,
        C_9_ce0,
        C_9_q0,
        C_10_address0,
        C_10_ce0,
        C_10_q0,
        C_11_address0,
        C_11_ce0,
        C_11_q0,
        C_12_address0,
        C_12_ce0,
        C_12_q0,
        C_13_address0,
        C_13_ce0,
        C_13_q0,
        C_14_address0,
        C_14_ce0,
        C_14_q0,
        C_15_address0,
        C_15_ce0,
        C_15_q0,
        stream_out_TDATA,
        stream_out_TVALID,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   stream_out_TREADY;
output  [9:0] C_address0;
output   C_ce0;
input  [31:0] C_q0;
output  [9:0] C_1_address0;
output   C_1_ce0;
input  [31:0] C_1_q0;
output  [9:0] C_2_address0;
output   C_2_ce0;
input  [31:0] C_2_q0;
output  [9:0] C_3_address0;
output   C_3_ce0;
input  [31:0] C_3_q0;
output  [9:0] C_4_address0;
output   C_4_ce0;
input  [31:0] C_4_q0;
output  [9:0] C_5_address0;
output   C_5_ce0;
input  [31:0] C_5_q0;
output  [9:0] C_6_address0;
output   C_6_ce0;
input  [31:0] C_6_q0;
output  [9:0] C_7_address0;
output   C_7_ce0;
input  [31:0] C_7_q0;
output  [9:0] C_8_address0;
output   C_8_ce0;
input  [31:0] C_8_q0;
output  [9:0] C_9_address0;
output   C_9_ce0;
input  [31:0] C_9_q0;
output  [9:0] C_10_address0;
output   C_10_ce0;
input  [31:0] C_10_q0;
output  [9:0] C_11_address0;
output   C_11_ce0;
input  [31:0] C_11_q0;
output  [9:0] C_12_address0;
output   C_12_ce0;
input  [31:0] C_12_q0;
output  [9:0] C_13_address0;
output   C_13_ce0;
input  [31:0] C_13_q0;
output  [9:0] C_14_address0;
output   C_14_ce0;
input  [31:0] C_14_q0;
output  [9:0] C_15_address0;
output   C_15_ce0;
input  [31:0] C_15_q0;
output  [31:0] stream_out_TDATA;
output   stream_out_TVALID;
output  [3:0] stream_out_TKEEP;
output  [3:0] stream_out_TSTRB;
output  [0:0] stream_out_TLAST;

reg ap_idle;
reg stream_out_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln64_fu_396_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_out_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] trunc_ln65_2_reg_704;
wire   [0:0] temp_last_fu_505_p2;
reg   [0:0] temp_last_reg_709;
wire   [63:0] zext_ln68_fu_469_p1;
reg   [7:0] j_fu_140;
wire   [7:0] add_ln65_fu_511_p2;
wire    ap_loop_init;
reg   [7:0] i_fu_144;
wire   [7:0] select_ln64_1_fu_439_p3;
reg   [14:0] indvar_flatten20_fu_148;
wire   [14:0] add_ln64_1_fu_402_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten20_load;
wire   [31:0] temp_data_fu_527_p35;
reg    ap_block_pp0_stage0_01001;
reg    C_ce0_local;
reg    C_1_ce0_local;
reg    C_2_ce0_local;
reg    C_3_ce0_local;
reg    C_4_ce0_local;
reg    C_5_ce0_local;
reg    C_6_ce0_local;
reg    C_7_ce0_local;
reg    C_8_ce0_local;
reg    C_9_ce0_local;
reg    C_10_ce0_local;
reg    C_11_ce0_local;
reg    C_12_ce0_local;
reg    C_13_ce0_local;
reg    C_14_ce0_local;
reg    C_15_ce0_local;
wire   [0:0] icmp_ln65_fu_425_p2;
wire   [7:0] add_ln64_fu_419_p2;
wire   [7:0] select_ln64_fu_431_p3;
wire   [6:0] empty_fu_447_p1;
wire   [2:0] trunc_ln65_fu_457_p1;
wire   [9:0] tmp_s_fu_461_p3;
wire   [0:0] cmp86_fu_451_p2;
wire   [0:0] icmp_ln69_fu_499_p2;
wire   [31:0] temp_data_fu_527_p33;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] temp_data_fu_527_p1;
wire   [3:0] temp_data_fu_527_p3;
wire   [3:0] temp_data_fu_527_p5;
wire   [3:0] temp_data_fu_527_p7;
wire   [3:0] temp_data_fu_527_p9;
wire   [3:0] temp_data_fu_527_p11;
wire   [3:0] temp_data_fu_527_p13;
wire   [3:0] temp_data_fu_527_p15;
wire  signed [3:0] temp_data_fu_527_p17;
wire  signed [3:0] temp_data_fu_527_p19;
wire  signed [3:0] temp_data_fu_527_p21;
wire  signed [3:0] temp_data_fu_527_p23;
wire  signed [3:0] temp_data_fu_527_p25;
wire  signed [3:0] temp_data_fu_527_p27;
wire  signed [3:0] temp_data_fu_527_p29;
wire  signed [3:0] temp_data_fu_527_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_140 = 8'd0;
#0 i_fu_144 = 8'd0;
#0 indvar_flatten20_fu_148 = 15'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) matmul_hls_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U122(
    .din0(C_q0),
    .din1(C_1_q0),
    .din2(C_2_q0),
    .din3(C_3_q0),
    .din4(C_4_q0),
    .din5(C_5_q0),
    .din6(C_6_q0),
    .din7(C_7_q0),
    .din8(C_8_q0),
    .din9(C_9_q0),
    .din10(C_10_q0),
    .din11(C_11_q0),
    .din12(C_12_q0),
    .din13(C_13_q0),
    .din14(C_14_q0),
    .din15(C_15_q0),
    .def(temp_data_fu_527_p33),
    .sel(trunc_ln65_2_reg_704),
    .dout(temp_data_fu_527_p35)
);

matmul_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_144 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_144 <= select_ln64_1_fu_439_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln64_fu_396_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_148 <= add_ln64_1_fu_402_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_148 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_140 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_140 <= add_ln65_fu_511_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        temp_last_reg_709 <= temp_last_fu_505_p2;
        trunc_ln65_2_reg_704 <= {{select_ln64_fu_431_p3[6:3]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_10_ce0_local = 1'b1;
    end else begin
        C_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_11_ce0_local = 1'b1;
    end else begin
        C_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_12_ce0_local = 1'b1;
    end else begin
        C_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_13_ce0_local = 1'b1;
    end else begin
        C_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_14_ce0_local = 1'b1;
    end else begin
        C_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_15_ce0_local = 1'b1;
    end else begin
        C_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_1_ce0_local = 1'b1;
    end else begin
        C_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_2_ce0_local = 1'b1;
    end else begin
        C_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_3_ce0_local = 1'b1;
    end else begin
        C_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_4_ce0_local = 1'b1;
    end else begin
        C_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_5_ce0_local = 1'b1;
    end else begin
        C_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_6_ce0_local = 1'b1;
    end else begin
        C_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_7_ce0_local = 1'b1;
    end else begin
        C_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_8_ce0_local = 1'b1;
    end else begin
        C_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_9_ce0_local = 1'b1;
    end else begin
        C_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_ce0_local = 1'b1;
    end else begin
        C_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln64_fu_396_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        stream_out_TDATA_blk_n = stream_out_TREADY;
    end else begin
        stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        stream_out_TVALID = 1'b1;
    end else begin
        stream_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_10_address0 = zext_ln68_fu_469_p1;

assign C_10_ce0 = C_10_ce0_local;

assign C_11_address0 = zext_ln68_fu_469_p1;

assign C_11_ce0 = C_11_ce0_local;

assign C_12_address0 = zext_ln68_fu_469_p1;

assign C_12_ce0 = C_12_ce0_local;

assign C_13_address0 = zext_ln68_fu_469_p1;

assign C_13_ce0 = C_13_ce0_local;

assign C_14_address0 = zext_ln68_fu_469_p1;

assign C_14_ce0 = C_14_ce0_local;

assign C_15_address0 = zext_ln68_fu_469_p1;

assign C_15_ce0 = C_15_ce0_local;

assign C_1_address0 = zext_ln68_fu_469_p1;

assign C_1_ce0 = C_1_ce0_local;

assign C_2_address0 = zext_ln68_fu_469_p1;

assign C_2_ce0 = C_2_ce0_local;

assign C_3_address0 = zext_ln68_fu_469_p1;

assign C_3_ce0 = C_3_ce0_local;

assign C_4_address0 = zext_ln68_fu_469_p1;

assign C_4_ce0 = C_4_ce0_local;

assign C_5_address0 = zext_ln68_fu_469_p1;

assign C_5_ce0 = C_5_ce0_local;

assign C_6_address0 = zext_ln68_fu_469_p1;

assign C_6_ce0 = C_6_ce0_local;

assign C_7_address0 = zext_ln68_fu_469_p1;

assign C_7_ce0 = C_7_ce0_local;

assign C_8_address0 = zext_ln68_fu_469_p1;

assign C_8_ce0 = C_8_ce0_local;

assign C_9_address0 = zext_ln68_fu_469_p1;

assign C_9_ce0 = C_9_ce0_local;

assign C_address0 = zext_ln68_fu_469_p1;

assign C_ce0 = C_ce0_local;

assign add_ln64_1_fu_402_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 15'd1);

assign add_ln64_fu_419_p2 = (i_fu_144 + 8'd1);

assign add_ln65_fu_511_p2 = (select_ln64_fu_431_p3 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((stream_out_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((stream_out_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (stream_out_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cmp86_fu_451_p2 = ((select_ln64_1_fu_439_p3 == 8'd127) ? 1'b1 : 1'b0);

assign empty_fu_447_p1 = select_ln64_1_fu_439_p3[6:0];

assign icmp_ln64_fu_396_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_425_p2 = ((j_fu_140 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_499_p2 = ((select_ln64_fu_431_p3 == 8'd127) ? 1'b1 : 1'b0);

assign select_ln64_1_fu_439_p3 = ((icmp_ln65_fu_425_p2[0:0] == 1'b1) ? add_ln64_fu_419_p2 : i_fu_144);

assign select_ln64_fu_431_p3 = ((icmp_ln65_fu_425_p2[0:0] == 1'b1) ? 8'd0 : j_fu_140);

assign stream_out_TDATA = temp_data_fu_527_p35;

assign stream_out_TKEEP = 4'd15;

assign stream_out_TLAST = temp_last_reg_709;

assign stream_out_TSTRB = 4'd15;

assign temp_data_fu_527_p33 = 'bx;

assign temp_last_fu_505_p2 = (icmp_ln69_fu_499_p2 & cmp86_fu_451_p2);

assign tmp_s_fu_461_p3 = {{empty_fu_447_p1}, {trunc_ln65_fu_457_p1}};

assign trunc_ln65_fu_457_p1 = select_ln64_fu_431_p3[2:0];

assign zext_ln68_fu_469_p1 = tmp_s_fu_461_p3;

endmodule //matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_64_8_VITIS_LOOP_65_9
