-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_64_8_VITIS_LOOP_65_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    C_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_ce0 : OUT STD_LOGIC;
    C_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_1_ce0 : OUT STD_LOGIC;
    C_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_2_ce0 : OUT STD_LOGIC;
    C_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_3_ce0 : OUT STD_LOGIC;
    C_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_4_ce0 : OUT STD_LOGIC;
    C_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_5_ce0 : OUT STD_LOGIC;
    C_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_6_ce0 : OUT STD_LOGIC;
    C_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_7_ce0 : OUT STD_LOGIC;
    C_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_8_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_8_ce0 : OUT STD_LOGIC;
    C_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_9_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_9_ce0 : OUT STD_LOGIC;
    C_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_10_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_10_ce0 : OUT STD_LOGIC;
    C_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_11_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_11_ce0 : OUT STD_LOGIC;
    C_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_12_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_12_ce0 : OUT STD_LOGIC;
    C_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_13_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_13_ce0 : OUT STD_LOGIC;
    C_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_14_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_14_ce0 : OUT STD_LOGIC;
    C_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    C_15_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    C_15_ce0 : OUT STD_LOGIC;
    C_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matmul_hls_matmul_hls_Pipeline_VITIS_LOOP_64_8_VITIS_LOOP_65_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln64_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln65_2_reg_704 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_last_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_last_reg_709 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln68_fu_469_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_140 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln65_fu_511_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln64_1_fu_439_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal indvar_flatten20_fu_148 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln64_1_fu_402_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten20_load : STD_LOGIC_VECTOR (14 downto 0);
    signal temp_data_fu_527_p35 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal C_ce0_local : STD_LOGIC;
    signal C_1_ce0_local : STD_LOGIC;
    signal C_2_ce0_local : STD_LOGIC;
    signal C_3_ce0_local : STD_LOGIC;
    signal C_4_ce0_local : STD_LOGIC;
    signal C_5_ce0_local : STD_LOGIC;
    signal C_6_ce0_local : STD_LOGIC;
    signal C_7_ce0_local : STD_LOGIC;
    signal C_8_ce0_local : STD_LOGIC;
    signal C_9_ce0_local : STD_LOGIC;
    signal C_10_ce0_local : STD_LOGIC;
    signal C_11_ce0_local : STD_LOGIC;
    signal C_12_ce0_local : STD_LOGIC;
    signal C_13_ce0_local : STD_LOGIC;
    signal C_14_ce0_local : STD_LOGIC;
    signal C_15_ce0_local : STD_LOGIC;
    signal icmp_ln65_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln64_fu_419_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln64_fu_431_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_447_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln65_fu_457_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_s_fu_461_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal cmp86_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_data_fu_527_p33 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal temp_data_fu_527_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal temp_data_fu_527_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component matmul_hls_sparsemux_33_4_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matmul_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_33_4_32_1_1_U122 : component matmul_hls_sparsemux_33_4_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 32,
        CASE1 => "0001",
        din1_WIDTH => 32,
        CASE2 => "0010",
        din2_WIDTH => 32,
        CASE3 => "0011",
        din3_WIDTH => 32,
        CASE4 => "0100",
        din4_WIDTH => 32,
        CASE5 => "0101",
        din5_WIDTH => 32,
        CASE6 => "0110",
        din6_WIDTH => 32,
        CASE7 => "0111",
        din7_WIDTH => 32,
        CASE8 => "1000",
        din8_WIDTH => 32,
        CASE9 => "1001",
        din9_WIDTH => 32,
        CASE10 => "1010",
        din10_WIDTH => 32,
        CASE11 => "1011",
        din11_WIDTH => 32,
        CASE12 => "1100",
        din12_WIDTH => 32,
        CASE13 => "1101",
        din13_WIDTH => 32,
        CASE14 => "1110",
        din14_WIDTH => 32,
        CASE15 => "1111",
        din15_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => C_q0,
        din1 => C_1_q0,
        din2 => C_2_q0,
        din3 => C_3_q0,
        din4 => C_4_q0,
        din5 => C_5_q0,
        din6 => C_6_q0,
        din7 => C_7_q0,
        din8 => C_8_q0,
        din9 => C_9_q0,
        din10 => C_10_q0,
        din11 => C_11_q0,
        din12 => C_12_q0,
        din13 => C_13_q0,
        din14 => C_14_q0,
        din15 => C_15_q0,
        def => temp_data_fu_527_p33,
        sel => trunc_ln65_2_reg_704,
        dout => temp_data_fu_527_p35);

    flow_control_loop_pipe_sequential_init_U : component matmul_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_144 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_144 <= select_ln64_1_fu_439_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten20_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln64_fu_396_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten20_fu_148 <= add_ln64_1_fu_402_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten20_fu_148 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_140 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_140 <= add_ln65_fu_511_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                temp_last_reg_709 <= temp_last_fu_505_p2;
                trunc_ln65_2_reg_704 <= select_ln64_fu_431_p3(6 downto 3);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    C_10_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_10_ce0 <= C_10_ce0_local;

    C_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_10_ce0_local <= ap_const_logic_1;
        else 
            C_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_11_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_11_ce0 <= C_11_ce0_local;

    C_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_11_ce0_local <= ap_const_logic_1;
        else 
            C_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_12_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_12_ce0 <= C_12_ce0_local;

    C_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_12_ce0_local <= ap_const_logic_1;
        else 
            C_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_13_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_13_ce0 <= C_13_ce0_local;

    C_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_13_ce0_local <= ap_const_logic_1;
        else 
            C_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_14_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_14_ce0 <= C_14_ce0_local;

    C_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_14_ce0_local <= ap_const_logic_1;
        else 
            C_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_15_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_15_ce0 <= C_15_ce0_local;

    C_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_15_ce0_local <= ap_const_logic_1;
        else 
            C_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_1_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_1_ce0 <= C_1_ce0_local;

    C_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_1_ce0_local <= ap_const_logic_1;
        else 
            C_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_2_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_2_ce0 <= C_2_ce0_local;

    C_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_2_ce0_local <= ap_const_logic_1;
        else 
            C_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_3_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_3_ce0 <= C_3_ce0_local;

    C_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_3_ce0_local <= ap_const_logic_1;
        else 
            C_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_4_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_4_ce0 <= C_4_ce0_local;

    C_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_4_ce0_local <= ap_const_logic_1;
        else 
            C_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_5_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_5_ce0 <= C_5_ce0_local;

    C_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_5_ce0_local <= ap_const_logic_1;
        else 
            C_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_6_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_6_ce0 <= C_6_ce0_local;

    C_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_6_ce0_local <= ap_const_logic_1;
        else 
            C_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_7_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_7_ce0 <= C_7_ce0_local;

    C_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_7_ce0_local <= ap_const_logic_1;
        else 
            C_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_8_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_8_ce0 <= C_8_ce0_local;

    C_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_8_ce0_local <= ap_const_logic_1;
        else 
            C_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_9_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_9_ce0 <= C_9_ce0_local;

    C_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_9_ce0_local <= ap_const_logic_1;
        else 
            C_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    C_address0 <= zext_ln68_fu_469_p1(10 - 1 downto 0);
    C_ce0 <= C_ce0_local;

    C_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            C_ce0_local <= ap_const_logic_1;
        else 
            C_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln64_1_fu_402_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten20_load) + unsigned(ap_const_lv15_1));
    add_ln64_fu_419_p2 <= std_logic_vector(unsigned(i_fu_144) + unsigned(ap_const_lv8_1));
    add_ln65_fu_511_p2 <= std_logic_vector(unsigned(select_ln64_fu_431_p3) + unsigned(ap_const_lv8_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, stream_out_TREADY, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((stream_out_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, stream_out_TREADY, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((stream_out_TREADY = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(stream_out_TREADY)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (stream_out_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln64_fu_396_p2)
    begin
        if (((icmp_ln64_fu_396_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten20_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten20_fu_148)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten20_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten20_load <= indvar_flatten20_fu_148;
        end if; 
    end process;

    cmp86_fu_451_p2 <= "1" when (select_ln64_1_fu_439_p3 = ap_const_lv8_7F) else "0";
    empty_fu_447_p1 <= select_ln64_1_fu_439_p3(7 - 1 downto 0);
    icmp_ln64_fu_396_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten20_load = ap_const_lv15_4000) else "0";
    icmp_ln65_fu_425_p2 <= "1" when (j_fu_140 = ap_const_lv8_80) else "0";
    icmp_ln69_fu_499_p2 <= "1" when (select_ln64_fu_431_p3 = ap_const_lv8_7F) else "0";
    select_ln64_1_fu_439_p3 <= 
        add_ln64_fu_419_p2 when (icmp_ln65_fu_425_p2(0) = '1') else 
        i_fu_144;
    select_ln64_fu_431_p3 <= 
        ap_const_lv8_0 when (icmp_ln65_fu_425_p2(0) = '1') else 
        j_fu_140;
    stream_out_TDATA <= temp_data_fu_527_p35;

    stream_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, stream_out_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_out_TDATA_blk_n <= stream_out_TREADY;
        else 
            stream_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_out_TKEEP <= ap_const_lv4_F;
    stream_out_TLAST <= temp_last_reg_709;
    stream_out_TSTRB <= ap_const_lv4_F;

    stream_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            stream_out_TVALID <= ap_const_logic_1;
        else 
            stream_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    temp_data_fu_527_p33 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    temp_last_fu_505_p2 <= (icmp_ln69_fu_499_p2 and cmp86_fu_451_p2);
    tmp_s_fu_461_p3 <= (empty_fu_447_p1 & trunc_ln65_fu_457_p1);
    trunc_ln65_fu_457_p1 <= select_ln64_fu_431_p3(3 - 1 downto 0);
    zext_ln68_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_461_p3),64));
end behav;
